---
name: Build and deploy to Netlify

"on":
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NETLIFY_SITE_ID: classy-paletas-f45a67
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    steps:
      - uses: >-
          actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        # v4.2.2
      - uses: >-
          actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        # v4.4.0
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - run: npm install -g netlify-cli
      - run: >-
          netlify deploy --prod --dir=build --site="$NETLIFY_SITE_ID"
          --auth="$NETLIFY_AUTH_TOKEN"
